# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 174f89dd425dd108a38467de1454f56cbe916c14d813bba6baac9043aff29dd68784d25da7a5227c4156b815b60fed096f3af7af7498bdfb1656815d8f86a513

test:
  secret_key_base: d70322c052a87713b9adabe26c9ffe7b3bad2b3b9264341860afc3691d0e921725c2ef5e6596edaa1bdfb1d7a30d05e409a466500211e9bd646d4fb22ea0aba5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
